### ISSUE TITLE
system.platform not available in Micropython

### ISSUE THREAD

**Issue by dhallgb** [yy502/ePaperDisplay#1]
I want to use your library on an embedded Micropython board, the WiPy. Micropython does not have the **platform** library, but does have the **sys** library, as do other implementations of Python based on CPython. Calls to **sys.implementation** return 'linux2', 'linux', 'darwin', or 'micropython' according to the list at http://stackoverflow.com/questions/446209/possible-values-from-sys-platform.

Would establishing the environment with **sys.implementation** be as adequate as using the **platform** library?

**Comment by yy502** [comment]
I'm lazy, so I use platform.system() to auto-determine what device (path) to use as seen here:

``` Python
MAC = "/dev/cu.usbserial"
LINUX = "/dev/ttyUSB0"
DEV = ""

if system()=='Linux':
    DEV = LINUX
elif system()=='Darwin':
    DEV = MAC
else:
    DEV = raw_input('Define serial port for EPD connection (e.g. /dev/ttyUSB1 or just hit enter for none): ')
```

Since you are using it on an embedded Micropython board, DEV should be set to a constant hence you don't need this block and the lib at all. So line 10-19 become:

``` Python
DEV = "/path/to/your/device/or/port"
```

and remove line 4.

**Comment by dhallgb** [comment]
Excellent, thank you.
