### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by BINCODINGD** [yy502/ePaperDisplay#3]
Hi, I'm a student.
I really need your help...
I tried your code "4_level_gray_4bpp_BMP_converter.py"

and I did like that you said
convert in.png -colorspace gray +matte -colors 4 -depth 2 -resize '800x600>' pgm:- | ./4_level_gray_4bpp_BMP_converter.py > out.bmp

but I have an error

File "./epaper.py", line 58, in <module>
    width = int(data[DIMENTIONS].strip().split(' ')[0])
IndexError: list index out of range

I don't know what problem is. I think your code may be right... Is covert command changed? 
I really need your help...
If you give me solution, I will be happy so much..
Thanks!!!

**Comment by yy502** [comment]
hi,

Try the converter scripts in my repo as-is rather than running the command you mentioned above. Does it throw any exception?

**Comment by BINCODINGD** [comment]
Thank your comment.
you mean just only python file?(I don't know about python at all but C++)

I did like below that
     Binui-MacBook-Pro:ePaperDisplay-master binsu$ python ePaper.py

and There is not any exception.

**Comment by yy502** [comment]
hi, I meant to use my Bash script to convert the image as described in the README. Let me know how it goes.

**Comment by BINCODINGD** [comment]
Thank you so much! It works:D!!

I'm trying e-paper without wifi connection.
Your code will help me. I'm happy. thanks!

**Comment by yy502** [comment]
Great to know :-)
