### ISSUE TITLE
without Wifi connection

### ISSUE THREAD

**Issue by BINCODINGD** [yy502/ePaperDisplay#4]
Could I ask a few question about code without Wifi function?
If you advise me, I will so thank you.

I want to connect e-paper device directly using rasberry pi3.
Could I control and upload the picture on e-paper without wifi module
What should I fix for removing wifi function in your code?

Thank you:)

**Comment by yy502** [comment]
It is impossible to upload images without using SD card.

Find out what your serial interface is on RPi3 and put in https://github.com/yy502/ePaperDisplay/blob/master/epd.py#L17 No need to remove any code.

**Comment by BINCODINGD** [comment]
Sorry.. I have not found serial port yet... What I need for finding serial port...?
What kind of format? (/dev/serial1 like that?)

Do I need usb serial device?

**Comment by yy502** [comment]
when you follow the instructions to enable the serial port on RPi, you will know which device to use. it will look like '/dev/ttyxxx'

**Comment by yy502** [comment]
no, you won't need a USB serial adapter. connect RX, TX and ground GPIOs to the epaper module.

**Comment by yy502** [comment]
in fact, you will use the 3.3V gpio to power the epaper module, so use 4 wires to connect the epaper to RPi.

**Comment by BINCODINGD** [comment]
I used ls /dev/tty*.
When I didn't use USB serial adapter, any path didn't appear.(I don't know why TT)
but When I used USB serial adapter, I could see appearing new path /dev/ttyUSB0.
So, I used USB serial adapter and I can see your code on ePaper.

Should I put BMP file in SD card manually or could I upload using rasberrypi?

(It will be last question... Thank you for your kindness)

**Comment by yy502** [comment]
it means you haven't enable serial port on your rpi. Google how to enable it. 

The FACE.BMP is just an image I uploaded to the epaper module for demo. You will need to upload your own using sd card.

**Comment by BINCODINGD** [comment]
Thank you so much!! I solved it:D
Full of good things with you all the time.

**Comment by yy502** [comment]
my pleasure :-)
