### ISSUE TITLE
The BITMAP doesn't produce any effects

### ISSUE THREAD

**Issue by luciust** [yy502/ePaperDisplay#5]
Hi, I've used Rasbperry Pi with Raspbian to run the code. 
Hardware: /dev/ttyAMA0 - standard 3,3V RPi UART, the screen is powered from RPi too.

All functions execute properly, and correct me if I'm wrong but the BMP can be only displayed after it's been copied to internal NAND FLASH of the screen?

**Comment by yy502** [comment]
Hi, yes, the BMP images must be copied to the internal storage via SD card first. 

see: https://github.com/yy502/ePaperDisplay#notes-on-file-management
